export type PopsAreaId =
  | "recepcao_comercial"
  | "medico"
  | "gestao"
  | "enfermagem"
  | "higienizacao_limpeza"
  | "copa_nutricao"
  | "financeiro_administrativo";

export type PopsArea = {
  id: PopsAreaId;
  label: string;
  descricao: string;
  foco: string;
  responsaveis: string[];
  tarefasDoDia: string[];
};

export type FluxogramaDocumento = {
  id: string;
  areaId: PopsAreaId;
  titulo: string;
  setor: string;
  responsavel: string;
  categoria: string;
  resumo: string;
  etapas: string[];
  tarefasSugeridas: string[];
  tags: string[];
  fileName: string;
  assetPath: string;
};

function fluxogramaPath(fileName: string) {
  return `${import.meta.env.BASE_URL}fluxogramas/${encodeURIComponent(fileName)}`;
}

export const popsAreas: PopsArea[] = [
  {
    id: "recepcao_comercial",
    label: "Recepção / Comercial",
    descricao: "Captação, qualificação, acolhimento, documentação, contratos e pós-venda.",
    foco: "Garantir uma jornada premium do primeiro contato até o acompanhamento.",
    responsaveis: ["Recepcionista", "Secretaria / Concierge", "Comercial"],
    tarefasDoDia: [
      "Confirmar consultas D-2 e D-1 e registrar no iClinic/PDCA Comercial.",
      "Acolher paciente, questionário, bioimpedância e encaminhamento à consulta.",
      "Conferir contratos no SuperSign antes do envio e acompanhar assinaturas.",
      "Registrar adesão, não adesão, presente e responsável pelo paciente.",
      "Fazer pós-venda D+1 e manter acompanhamento semanal quando aplicável.",
    ],
  },
  {
    // SETOR MÉDICO (10/09/2026): o documento "Fluxogramas por Setor" traz o fluxo
    // do médico, que não tinha área no app — vivia sem lugar entre Gestão e Vendas.
    id: "medico",
    label: "Médico / Profissional",
    descricao: "Consulta, prescrição, plano dos próximos meses e entrega das receitas.",
    foco: "Sair da consulta com prescrição, exames e plano registrados — e o paciente pronto para Vendas.",
    responsaveis: ["Dr. Daniel", "Profissionais assistentes"],
    tarefasDoDia: [
      "Receber o paciente que vem da bioimpedância e realizar a consulta.",
      "Enviar ao grupo PRESCRIÇÃO: receitas + exames.",
      "Enviar ao grupo TRATAMENTO: o plano dos próximos meses.",
      "Memed: receitas ao paciente e próximos exames individualizados registrados.",
      "Imprimir e entregar as vias físicas — o paciente segue para Vendas.",
      "Paciente que NÃO fechou: contato em D+1 para entender a objeção e ajustar o possível.",
    ],
  },
  {
    id: "gestao",
    label: "Gestão",
    descricao: "Coordenação da experiência pré e pós-consulta, conferência e não adesão.",
    foco: "Tirar ruído entre recepção, médico, enfermagem e entrega final.",
    responsaveis: ["Gestor", "Secretaria Executiva", "Coordenação"],
    tarefasDoDia: [
      "Conferir pré-consulta: cadastro, assinatura, documentos e bioimpedância.",
      "Validar contrato, prontuário físico e entrega final antes de liberar o paciente.",
      "Acompanhar não adesões e direcionar receitas conforme regra definida.",
      "Garantir entrega de plano, presente e orientação final pela enfermagem.",
    ],
  },
  {
    id: "enfermagem",
    label: "Enfermagem",
    descricao: "Procedimentos, medicações, estoque, esterilização, emergências e acompanhamento.",
    foco: "Executar com segurança, rastreabilidade e registro obrigatório.",
    responsaveis: ["Enfermeira", "Equipe de Enfermagem", "Dr. Daniel"],
    tarefasDoDia: [
      "Conferir prescrições, materiais, EPIs, sala e identificação do paciente.",
      "Registrar medicações, flebotomia, intercorrências e procedimentos no sistema correto.",
      "Atualizar acompanhamento de pacientes em tratamento, doses e bioimpedância.",
      "Controlar estoque: mínimo, vencimentos, compras, recebimento e entrada no iClinic.",
      "Garantir esterilização, descarte e disponibilidade do DEA.",
    ],
  },
  {
    id: "higienizacao_limpeza",
    label: "Higienização / Limpeza",
    descricao: "Limpeza concorrente/terminal, saneantes, EPIs e controle de geladeira.",
    foco: "Manter ambientes seguros e registrar conformidade.",
    responsaveis: ["Limpeza", "Higienização"],
    tarefasDoDia: [
      "Classificar ambientes e aplicar limpeza conforme criticidade.",
      "Usar EPIs, saneantes corretos e registrar checklist.",
      "Controlar temperatura da geladeira e agir quando sair da faixa.",
    ],
  },
  {
    id: "copa_nutricao",
    label: "Copa / Nutrição",
    descricao: "Alimentos prontos, lanches, validade, etiquetagem e rastreabilidade.",
    foco: "Oferecer alimentos seguros, identificados e dentro do padrão.",
    responsaveis: ["Copa", "Nutrição", "Recepção"],
    tarefasDoDia: [
      "Conferir validade, temperatura, higiene da bancada e insumos antes da montagem.",
      "Higienizar frutas, montar, embalar, etiquetar e refrigerar imediatamente.",
      "Registrar rastreabilidade na planilha integrada quando houver oferta ao paciente.",
    ],
  },
  {
    id: "financeiro_administrativo",
    label: "Financeiro / Administrativo",
    descricao: "Fechamento diário, conciliação, notas, compras, reembolso e arquivamento.",
    foco: "Preservar rastreabilidade de ponta a ponta no movimento financeiro.",
    responsaveis: ["Gestor Financeiro", "Financeiro", "Administrativo"],
    tarefasDoDia: [
      "Coletar comandas, receitas, comprovantes, contratos e documentos do crediário.",
      "Conferir valores, meios de pagamento, taxas, rendimentos e travas de caixa.",
      "Atualizar planilhas, PDCA Comercial, P12, NFS-e e arquivos no SharePoint.",
      "Validar compras institucionais com NF/invoice, comprovante, formulário e destino.",
    ],
  },
];

export const fluxogramas: FluxogramaDocumento[] = [
  // ---------------------------------------------------------------------------
  // ENTRADA DE 10/09/2026 (Lucas: "colocar esses pops e fluxogramas no app").
  // Os fluxogramas vinham dentro de .docx (que o app não abre): foram extraídos
  // como imagem. O POP de Agendamento de Consultas do pacote já estava aqui
  // (arquivo idêntico) e não foi duplicado.
  // ---------------------------------------------------------------------------
  {
    id: "fluxo-captacao-instagram",
    areaId: "recepcao_comercial",
    titulo: "Fluxo de Captação de Pacientes — Instagram",
    setor: "Comercial / Marketing",
    responsavel: "Secretário (prospecção) · Lucas (feed) · Dr. Daniel (Stories)",
    categoria: "Manual operacional + fluxograma",
    resumo:
      "Prospecção ativa nos perfis @dr.danielbratan e @institutobratan: 20 a 30 perfis qualificados por dia, abordagem com contexto e pergunta aberta — nunca oferecendo consulta de entrada. A consulta só é apresentada depois do SIM. Follow-up D2/D3/D5 e, sem resposta, arquivar sem insistir.",
    etapas: [
      "Início do dia — mapear leads",
      "Qualificação — 20 a 30 perfis/dia",
      "Abordagem personalizada",
      "Descoberta de necessidade",
      "Oferta da avaliação",
      "Agendamento",
      "Registro + indicadores",
    ],
    tarefasSugeridas: [
      "Nunca começar oferecendo consulta: 1ª mensagem = contexto + boas-vindas + pergunta aberta.",
      "Follow-up D2 (interação natural), D3 (mensagem curta), D5 (último contato) — depois arquivar.",
      "Garantir os 2 Stories diários do Instituto: 1 de autoridade/prova + 1 de conversão.",
      "Registrar cada lead na planilha e ler o funil semanal: abordagens → respostas → interessados → agendamentos → receita.",
      "Separar os indicadores do perfil do Dr. Daniel × perfil do Instituto (em 30 dias se sabe qual gera paciente).",
    ],
    tags: ["instagram", "captação", "prospecção", "follow-up", "funil", "stories", "comercial"],
    fileName: "Fluxograma — Captacao de Pacientes no Instagram.png",
    assetPath: fluxogramaPath("Fluxograma — Captacao de Pacientes no Instagram.png"),
  },
  {
    id: "fluxo-atendimento-whatsapp-crm",
    areaId: "recepcao_comercial",
    titulo: "Fluxo de Atendimento — WhatsApp & CRM (jornada do lead)",
    setor: "Recepção / Agendamento",
    responsavel: "Quem atende o WhatsApp da clínica",
    categoria: "Fluxograma + jornada explicada",
    resumo:
      "Do primeiro WhatsApp à consulta realizada, com SLA de 8 minutos e textos-padrão T1 a T12. Ramo A (agendou): sinal de R$ 500 → guia e questionário → confirmação 48h/24h → consulta. Ramo B (não agendou): follow-up D+1, D+3, D+7 e repescagem mensal pela etiqueta do mês.",
    etapas: [
      "Nova mensagem no WhatsApp",
      "Registrar no CRM (Kanban)",
      "Responder em até 8 minutos (T1)",
      "Dúvidas + provas sociais (T2, T3, T5)",
      "Valores e proposta de agenda (T4, T6, T7)",
      "Ramo A — sinal, guia, confirmação, consulta",
      "Ramo B — follow-up D+1/D+3/D+7 e repescagem",
    ],
    tarefasSugeridas: [
      "Responder em até 8 minutos no horário comercial; atrasou, reconhecer com o T8 (nunca inventar justificativa).",
      "Origem desconhecida entra como \"Não informado\" — nunca preencher por suposição (dado errado é pior que dado vazio).",
      "Valor só depois do diferencial: T4 (consulta R$ 2.500 com mapeamento) e T6 (sinal R$ 500 + \"manhã ou tarde?\").",
      "E-mail só é pedido no momento da guia (T12), quando passa a ter uso real.",
      "Dr. Daniel é médico nutrólogo — nunca \"endocrinologista\"; nada de promessa de resultado ou medicação por WhatsApp.",
    ],
    tags: ["whatsapp", "crm", "lead", "sla", "t1-t12", "follow-up", "repescagem", "sinal"],
    fileName: "Fluxograma — Atendimento WhatsApp e CRM (jornada do lead).png",
    assetPath: fluxogramaPath("Fluxograma — Atendimento WhatsApp e CRM (jornada do lead).png"),
  },
  {
    id: "modelo-scripts-bratan",
    areaId: "recepcao_comercial",
    titulo: "Modelo de Scripts — Instituto Bratan",
    setor: "Comercial / Recepção",
    responsavel: "Quem fala com o paciente (telefone e mensagem)",
    categoria: "Biblioteca de scripts",
    resumo:
      "Os 15 scripts da jornada: conversão de lead por telefone e por mensagem, boas-vindas, confirmação após pagamento, lembrete D-1, preparo, reagendamento, pós-consulta, os quatro resgates (lead, cancelada, no-show, não voltou), régua de relacionamento, objeções com resposta e os erros a evitar.",
    etapas: [
      "Conversão de lead (telefone e mensagem)",
      "Boas-vindas e onboarding",
      "Confirmação, lembrete D-1 e preparo",
      "Reagendamento e pós-consulta",
      "Resgates: lead, cancelada, no-show, não voltou",
      "Régua de relacionamento",
      "Objeções e boas práticas",
    ],
    tarefasSugeridas: [
      "Escutar antes de apresentar: entender dor e objetivo antes de falar de método ou preço.",
      "Toda conversa termina com proposta clara de próximo passo.",
      "Escassez só com verdade — agenda concorrida é real, nunca inventar.",
      "Registrar objetivo, sintomas, objeções e histórico no CRM: o próximo contato precisa saber.",
      "Cuidar de quem disse não: o \"não\" de hoje pode ser o \"sim\" em 30 dias.",
    ],
    tags: ["scripts", "objeções", "telefone", "mensagem", "resgate", "régua", "comercial"],
    fileName: "Modelo de Scripts — Instituto Bratan.pdf",
    assetPath: fluxogramaPath("Modelo de Scripts — Instituto Bratan.pdf"),
  },
  {
    id: "pop-cobranca-assinatura-supersign-v2",
    areaId: "recepcao_comercial",
    titulo: "POP · Cobrança de Assinatura de Contratos (SuperSign) v2",
    setor: "Recepção",
    responsavel: "Recepção · escala para o Gestor (Estevão) e a Direção (Andrya)",
    categoria: "Procedimento + fluxograma",
    resumo:
      "Todo dia, do início da manhã ao meio-dia: listar os contratos pendentes no SuperSign e cobrar na escada D1 a D5 — áudio, texto, texto, ligação, verificação com o Gestor. Nenhum paciente fica em tratamento sem contrato assinado: sem assinatura não há respaldo jurídico.",
    etapas: [
      "SuperSign → Envelopes pendentes",
      "D1 · áudio + lembrete no SuperSign",
      "D2 · texto (extrema urgência)",
      "D3 · texto de reforço",
      "D4 · ligação e escalada ao Gestor",
      "D5 · verificação com o Gestor → Direção",
    ],
    tarefasSugeridas: [
      "No D1 usar ÁUDIO, não texto: o texto o vendedor já enviou; o áudio faz o paciente ouvir.",
      "Etiqueta verde \"Aguardando assinatura\" no WhatsApp — só remover quando assinar.",
      "Toda passagem ao Gestor ou à Direção por mensagem registrada (rastreabilidade).",
      "LGPD: só pelo aparelho/número CORPORATIVO da recepção — dado de saúde em aparelho pessoal é multa.",
      "Repetir a escada todos os dias para todos os pendentes; descumprir o fluxo gera advertência.",
    ],
    tags: ["supersign", "contrato", "assinatura", "d1-d5", "lgpd", "recepção", "pop"],
    fileName: "POP — Cobranca de Assinatura de Contratos (SuperSign) v2.pdf",
    assetPath: fluxogramaPath("POP — Cobranca de Assinatura de Contratos (SuperSign) v2.pdf"),
  },
  {
    id: "pop-rotina-diaria-celular-agendamentos-v1",
    areaId: "recepcao_comercial",
    titulo: "POP · Rotina Diária do Celular de Agendamentos (v1)",
    setor: "Agendamentos / Concierge",
    responsavel: "Quem opera o celular de agendamentos",
    categoria: "Procedimento + 8 fluxos",
    resumo:
      "O celular de agendamentos exige acompanhamento ATIVO, não é só canal de resposta. Primeiro horário zera pendências, a repescagem do dia anterior é obrigatória todos os dias, e o expediente só encerra depois da conferência das 8 perguntas. Toda segunda, varredura dos próximos 15 dias.",
    etapas: [
      "1 · Primeiro horário — zerar pendências",
      "2 · Repescagem do dia anterior (obrigatória)",
      "3 · Agendou consulta → Feegow + sinal + guia",
      "4 · Prometeu retorno → pendência ativa",
      "5 · Paciente antigo → ler histórico antes",
      "6 · Lead novo → D1 a D5 até o desfecho",
      "7 · Conferência das 8 perguntas",
      "8 · Segunda-feira — próximos 15 dias",
    ],
    tarefasSugeridas: [
      "Não iniciar tarefa nova antes de zerar as pendências do primeiro horário.",
      "Agendou? Lançar no Feegow na hora e cobrar o sinal na hora — nunca deixar para depois.",
      "Prometeu retorno? O paciente vira pendência ativa e nunca precisa cobrar o Instituto.",
      "Antes de responder paciente antigo, ler o histórico (cobrar sinal de quem tem isenção registrada custa a consulta).",
      "Encerrar o dia só depois da conferência: alguma resposta SIM → resolver agora ou marcar para a repescagem.",
    ],
    tags: ["agendamento", "repescagem", "feegow", "sinal", "conferência", "d1-d5", "pop"],
    fileName: "POP — Rotina Diaria do Celular de Agendamentos v1.pdf",
    assetPath: fluxogramaPath("POP — Rotina Diaria do Celular de Agendamentos v1.pdf"),
  },
  {
    id: "fluxograma-setor-medico",
    areaId: "medico",
    titulo: "Fluxograma · Setor Médico / Profissional",
    setor: "Médico",
    responsavel: "Dr. Daniel",
    categoria: "Fluxograma por setor",
    resumo:
      "Da bioimpedância à entrega das receitas: consulta, grupo PRESCRIÇÃO (receitas + exames), grupo TRATAMENTO (plano dos próximos meses), Memed e vias físicas — o paciente segue para Vendas. Trilha paralela: quem não fechou recebe contato em D+1 para entender a objeção.",
    etapas: [
      "Entrada: paciente vindo da bioimpedância",
      "Realiza a consulta",
      "Grupo PRESCRIÇÃO: receitas + exames",
      "Grupo TRATAMENTO: plano dos próximos meses",
      "Memed + vias físicas impressas",
      "Saída: paciente segue para Vendas",
    ],
    tarefasSugeridas: [
      "Enviar receitas e exames ao grupo PRESCRIÇÃO e o plano ao grupo TRATAMENTO.",
      "Memed: receitas ao paciente e próximos exames individualizados registrados.",
      "Imprimir e entregar as vias físicas antes de encaminhar a Vendas.",
      "Paciente que não fechou: contatar em D+1, entender a objeção e ajustar/reduzir o possível.",
      "Sem resposta do paciente: acionar o Gestor (Estevão) para novo contato em D+2.",
    ],
    tags: ["consulta", "prescrição", "memed", "receita", "objeção", "médico"],
    fileName: "Fluxograma — Setor Medico.png",
    assetPath: fluxogramaPath("Fluxograma — Setor Medico.png"),
  },
  {
    id: "fluxograma-setor-vendas",
    areaId: "recepcao_comercial",
    titulo: "Fluxograma · Setor de Vendas (Secretário-Vendedor)",
    setor: "Vendas",
    responsavel: "Secretário-Vendedor",
    categoria: "Fluxograma por setor",
    resumo:
      "Recebe o paciente do médico, imprime a prescrição, monta o Plano de Acompanhamento no template e apresenta o valor CHEIO antes de revelar o preço do Plano Bratan. Fechou: presente por faixa (R$ 7–10 mil caixa PO Box · acima de R$ 10 mil garrafa Stanley), Comanda/PMI preenchida e paciente à Recepção.",
    etapas: [
      "Entrada: paciente vindo do médico",
      "Imprime a prescrição e envia ao grupo FARMÁCIA",
      "Monta o Plano de Acompanhamento no template",
      "Apresenta o valor cheio → depois o Plano Bratan",
      "Fechou: presente + parabenização + Comanda/PMI",
      "Saída: paciente à Recepção · contato à Concierge",
    ],
    tarefasSugeridas: [
      "Apresentar o valor CHEIO primeiro; o preço do Plano Bratan vem depois.",
      "Presente só na 1ª consulta: R$ 7–10 mil caixa PO Box · acima de R$ 10 mil garrafa Stanley.",
      "Plano parcial é exceção de até 10%/mês — registrar o motivo na observação.",
      "Não fechou: registrar as objeções no Plano de Melhoria Individual e enviar contato + motivo ao médico.",
      "Enviar à Concierge o contato e o resumo do fechamento (fechou tudo / metade / não fechou).",
    ],
    tags: ["vendas", "plano bratan", "comanda", "pmi", "presente", "objeção", "fechamento"],
    fileName: "Fluxograma — Setor de Vendas — Secretario-Vendedor.png",
    assetPath: fluxogramaPath("Fluxograma — Setor de Vendas — Secretario-Vendedor.png"),
  },
  {
    id: "fluxograma-setor-recepcao",
    areaId: "recepcao_comercial",
    titulo: "Fluxograma · Setor de Recepção / Agendamento",
    setor: "Recepção",
    responsavel: "Recepção",
    categoria: "Fluxograma por setor",
    resumo:
      "Recebe o paciente de Vendas com café/água (POP de Excelência), solicita a Comanda/PMI e monta a agenda no iClinic por cor: Dr. Daniel (amarelo), nutricionista (laranja, 6 checkpoints com o 1º na mesma semana) e enfermagem (1ª bioimpedância e 1ª dose). Boas-vindas com todas as datas até 18h, contrato no SharePoint e PDF numerado no caderno azul.",
    etapas: [
      "Entrada: paciente vindo de Vendas",
      "Café/água — POP de Excelência",
      "Comanda/PMI com o vendedor",
      "iClinic: Dr. Daniel · nutricionista · enfermagem",
      "Boas-vindas com todas as datas (até 18h)",
      "Contrato + PDF numerado → Administradora",
    ],
    tarefasSugeridas: [
      "Cadência no iClinic: 6 meses = 2/2 · 9 meses = 3/3 · 12 meses = 4/4, com descrição \"x de y\".",
      "1º checkpoint da nutricionista na MESMA semana; enfermagem agenda a 1ª bioimpedância e a 1ª dose.",
      "Observações: exames 15 dias antes — o setor confere quais exames são necessários.",
      "Boas-vindas com todas as datas até 18h de hoje ou 12h do dia seguinte.",
      "Toda segunda: revisar os pacientes dos próximos 15 dias (cobrar exames, conferir coleta, sanar dúvidas).",
    ],
    tags: ["recepção", "iclinic", "agenda", "contrato", "sharepoint", "boas-vindas"],
    fileName: "Fluxograma — Setor de Recepcao e Agendamento.png",
    assetPath: fluxogramaPath("Fluxograma — Setor de Recepcao e Agendamento.png"),
  },
  {
    id: "fluxograma-setor-enfermagem",
    areaId: "enfermagem",
    titulo: "Fluxograma · Setor de Enfermagem",
    setor: "Enfermagem",
    responsavel: "Enfermagem (Juliana)",
    categoria: "Fluxograma por setor",
    resumo:
      "Do 1º atendimento (1ª aplicação e/ou 1ª bioimpedância) ao término do tratamento: agenda as demais sessões, manda mensagem no dia seguinte de CADA aplicação e mantém o bloco diário de 15h30–16h30 com mensagem-padrão a TODOS do dia anterior — vindos, faltas e reagendados — enviada até 18h.",
    etapas: [
      "Entrada: 1º atendimento (1ª aplicação/bioimpedância)",
      "Agenda as demais sessões (tratamento + bioimpedância)",
      "Mensagem no dia seguinte de cada aplicação",
      "Bloco diário 15h30–16h30 (envio até 18h)",
      "Tratamento concluído → grupo TÉRMINO",
      "Saída: Secretário confirma a próxima consulta",
    ],
    tarefasSugeridas: [
      "Depois de cada aplicação, mensagem no dia seguinte: como está e como respondeu à medicação.",
      "Bloco diário 15h30–16h30: mensagem-padrão a todos do dia anterior (vindos, faltas e reagendados), até 18h.",
      "Sem continuidade de tratamento: mensagem em D+1 desejando bom processo e encerrar até a próxima consulta.",
      "Tratamento concluído: avisar o grupo TÉRMINO quais sessões o paciente concluiu.",
    ],
    tags: ["enfermagem", "aplicação", "bioimpedância", "bloco diário", "término"],
    fileName: "Fluxograma — Setor de Enfermagem.png",
    assetPath: fluxogramaPath("Fluxograma — Setor de Enfermagem.png"),
  },
  {
    id: "fluxograma-setor-concierge",
    areaId: "recepcao_comercial",
    titulo: "Fluxograma · Setor de Concierge",
    setor: "Concierge",
    responsavel: "Concierge",
    categoria: "Fluxograma por setor",
    resumo:
      "Vendas envia o contato e o resumo do fechamento; na manhã seguinte (D+1) a Concierge manda as boas-vindas e pede a avaliação no Google. Sem resposta, reenvia no dia seguinte reforçando acolhimento, e fica à disposição para crítica construtiva ou elogio.",
    etapas: [
      "Entrada: Vendas envia contato + resumo do fechamento",
      "D+1 de manhã: boas-vindas + avaliação no Google",
      "Sem resposta: reenvio no dia seguinte",
      "À disposição para crítica ou elogio",
      "Encerra a trilha de boas-vindas",
    ],
    tarefasSugeridas: [
      "Boas-vindas na manhã do D+1, sempre com o pedido de avaliação no Google.",
      "Sem resposta: reenviar no dia seguinte reforçando acolhimento e disponibilidade.",
      "Manter-se à disposição para crítica construtiva ou elogio antes de encerrar a trilha.",
    ],
    tags: ["concierge", "boas-vindas", "google", "d+1", "experiência"],
    fileName: "Fluxograma — Setor de Concierge.png",
    assetPath: fluxogramaPath("Fluxograma — Setor de Concierge.png"),
  },
  {
    id: "fluxograma-setor-administrativo",
    areaId: "financeiro_administrativo",
    titulo: "Fluxograma · Setor Administrativo",
    setor: "Administrativo",
    responsavel: "Administradora",
    categoria: "Fluxograma por setor",
    resumo:
      "Recebe o contrato em PDF da Recepção e confere item a item como documento jurídico (dados, CID, sessões, valores, pagamento). Correto e autorizado: envia pelo SuperSign com prazo de contrato em mãos em até 24h. Errado: devolve à Recepção para refazer.",
    etapas: [
      "Entrada: Recepção envia o contrato em PDF",
      "Confere item a item (dados, CID, sessões, valores)",
      "Correto? → SuperSign, assinatura em até 24h",
      "Errado? → devolve à Recepção para correção",
      "Arquiva e encerra",
    ],
    tarefasSugeridas: [
      "Conferir o contrato item a item — é documento jurídico, não formulário.",
      "Aprovado: enviar pelo SuperSign com prazo de contrato em mãos em até 24h.",
      "Divergente: devolver à Recepção para refazer, sem enviar ao paciente.",
    ],
    tags: ["administrativo", "contrato", "supersign", "cid", "jurídico"],
    fileName: "Fluxograma — Setor Administrativo.png",
    assetPath: fluxogramaPath("Fluxograma — Setor Administrativo.png"),
  },
  {
    id: "pop-caminhada-paciente-v3",
    areaId: "gestao",
    titulo: "POP · Caminhada do Paciente (v3)",
    setor: "Todos os setores",
    responsavel: "Equipe operacional completa",
    categoria: "Documento unificado",
    resumo:
      "A caminhada completa do paciente — do pós-consulta ao pós-venda — por setor, com a Cadência D1–D5, o escalonamento ao Gestor (Estevão), a regra de ouro das reclamações e as mensagens-padrão. Registro oficial: Planilha de Cadências (no app, aba do CRM).",
    etapas: ["Cadência D1–D5", "Fluxo por setor", "Escalonamento ao Gestor", "Réguas contínuas", "Mensagens-padrão"],
    tarefasSugeridas: [
      "Todo contato ativo sem resposta abre a cadência D1–D5 — registrar cada D na Planilha de Cadências do CRM.",
      "Qualquer insatisfação vai à Concierge NO MESMO DIA (grave: Dr. Daniel → CEO).",
      "Sem resposta no D5 → o caso sobe sozinho para a trilha de 5 ligações do Estevão.",
      "Janelas de envio: Enfermagem 10h00–10h30 · Recepção e Concierge até 12h00.",
    ],
    tags: ["cadência", "d1-d5", "concierge", "gestor", "reclamação", "planilha", "pop"],
    fileName: "POP — Caminhada do Paciente v3.pdf",
    assetPath: fluxogramaPath("POP — Caminhada do Paciente v3.pdf"),
  },
  {
    id: "pop-agendamento-consultas-v1",
    areaId: "recepcao_comercial",
    titulo: "POP · Agendamento de Consultas e Tratamentos (v1)",
    setor: "Recepção / Agendamento",
    responsavel: "Recepção e time de agendamento",
    categoria: "Procedimento + fluxograma",
    resumo:
      "Toda consulta é marcada pelo TEMPO DO TRATAMENTO, não pelo calendário: Dr. Daniel 7–10 dias antes do fim do tratamento; Dra. Géssica na mesma semana da consulta médica (máx. 10 dias); bioimpedância junto; medicações em até 10 dias. Inclui o Plano Bratan e a Regra de Ouro da 1ª consulta.",
    etapas: ["Identifique o fechamento", "Programa de Acompanhamento", "Plano Bratan", "Exceções", "Regra de Ouro"],
    tarefasSugeridas: [
      "Agendar a próxima consulta do Dr. Daniel 7 a 10 dias ANTES do término do tratamento — nunca depois.",
      "1ª consulta da Dra. Géssica na mesma semana da consulta médica (máximo 10 dias).",
      "Paciente que não aceita agendar tudo → tarefa no CRM E pendência no Feegow (textos-padrão do POP).",
      "Todo paciente sai da 1ª consulta com Dr. Daniel + Dra. Géssica + bioimpedância agendados.",
    ],
    tags: ["agendamento", "feegow", "plano bratan", "tempo do tratamento", "recepção", "pop"],
    fileName: "POP — Agendamento de Consultas e Tratamentos v1.pdf",
    assetPath: fluxogramaPath("POP — Agendamento de Consultas e Tratamentos v1.pdf"),
  },
  {
    id: "administracao-medicamento-im",
    areaId: "enfermagem",
    titulo: "Administração de Medicamento - Via Intramuscular",
    setor: "Enfermagem",
    responsavel: "Equipe de Enfermagem",
    categoria: "Procedimento assistencial",
    resumo: "Técnica em Z para aplicação intramuscular segura, com preparo, técnica, descarte e registro.",
    etapas: ["Preparo", "Técnica e aplicação", "Pós e descarte", "Registro"],
    tarefasSugeridas: [
      "Conferir medicamento, dose, via, paciente e prescrição.",
      "Paramentar-se, aplicar técnica em Z, observar resposta por 30 minutos.",
      "Descartar perfurocortantes e registrar no prontuário eletrônico.",
    ],
    tags: ["medicação", "prescrição", "registro", "descarte"],
    fileName: "Fluxograma — Administracao de Medicamento — Via Intramuscular.png",
    assetPath: fluxogramaPath("Fluxograma — Administracao de Medicamento — Via Intramuscular.png"),
  },
  {
    id: "atendimento-clinica-vendas",
    areaId: "recepcao_comercial",
    titulo: "Atendimento na Clínica e Processo de Vendas",
    setor: "Recepção / Comercial",
    responsavel: "Recepcionista / Vendedor",
    categoria: "Jornada comercial",
    resumo: "Condução do paciente da chegada ao fechamento, documentação, contrato e início do tratamento.",
    etapas: ["Atendimento na clínica", "Decisão do paciente", "Registro e documentação", "Conferência e assinatura", "Início do tratamento"],
    tarefasSugeridas: [
      "Entregar questionário, direcionar bioimpedância e escanear documentos.",
      "Registrar fechamento ou não fechamento no prontuário.",
      "Emitir contrato, separar presente, conferir assinatura e arquivar contrato.",
    ],
    tags: ["recepção", "vendas", "contrato", "bioimpedância"],
    fileName: "Fluxograma — Atendimento na Clínica e Processo de Vendas.png",
    assetPath: fluxogramaPath("Fluxograma — Atendimento na Clínica e Processo de Vendas.png"),
  },
  {
    id: "boas-praticas-limpeza-desinfeccao",
    areaId: "higienizacao_limpeza",
    titulo: "Boas Práticas de Limpeza e Desinfecção",
    setor: "Higienização / Limpeza",
    responsavel: "Higienização",
    categoria: "Ambientes",
    resumo: "Higienização por criticidade, com saneantes corretos e registro em checklist.",
    etapas: ["Classificar e preparar", "Proteger e aplicar", "Esfregar e secar", "Inspecionar e registrar"],
    tarefasSugeridas: [
      "Classificar a área e definir limpeza concorrente ou terminal.",
      "Separar EPIs, detergente e hipoclorito.",
      "Inspecionar resultado, lavar EPIs e registrar checklist.",
    ],
    tags: ["limpeza", "desinfecção", "checklist", "EPI"],
    fileName: "Fluxograma — Boas Práticas de Limpeza e Desinfecção.png",
    assetPath: fluxogramaPath("Fluxograma — Boas Práticas de Limpeza e Desinfecção.png"),
  },
  {
    id: "compras-conta-pessoal-socios",
    areaId: "financeiro_administrativo",
    titulo: "Compras Institucionais via Conta Pessoal de Sócios",
    setor: "Financeiro",
    responsavel: "Setor Financeiro",
    categoria: "Compras e reembolso",
    resumo: "Compra sem NF-e nacional paga por sócio, com documentação, justificativa, reembolso e validação fiscal.",
    etapas: ["Elegibilidade", "Documentação", "Formulário e justificativa", "Reembolso e lançamento", "Arquivamento e validação"],
    tarefasSugeridas: [
      "Validar se a compra é pontual, institucional e permitida por CPF.",
      "Anexar pedido, documento fiscal aceito, tributos e comprovante de pagamento.",
      "Preencher formulário de reembolso, lançar natureza correta e arquivar processo completo.",
    ],
    tags: ["financeiro", "compras", "reembolso", "arquivo"],
    fileName: "Fluxograma — Compras Institucionais via Conta Pessoal de Sócios.png",
    assetPath: fluxogramaPath("Fluxograma — Compras Institucionais via Conta Pessoal de Sócios.png"),
  },
  {
    id: "contratos-supersign",
    areaId: "recepcao_comercial",
    titulo: "Contratos no SuperSign - Passo a Passo",
    setor: "Recepção / Comercial",
    responsavel: "Andrya Bratan",
    categoria: "Contratos",
    resumo: "Envio e assinatura digital de contratos no SuperSign, com ordem, autenticação por WhatsApp e conferência final.",
    etapas: ["Acesso e seleção", "Nomear envelope", "Participantes e autenticação", "Conferência e envio", "Execução e fechamento"],
    tarefasSugeridas: [
      "Selecionar modelo correto e nomear envelope no padrão.",
      "Conferir ordem de assinatura, contatos, WhatsApp e ausência de campos em branco.",
      "Acompanhar assinatura administrativa, empresa, paciente/colaborador e testemunhas.",
    ],
    tags: ["contrato", "SuperSign", "assinatura", "WhatsApp"],
    fileName: "Fluxograma — Contratos no SuperSing — Passo a Passo.png",
    assetPath: fluxogramaPath("Fluxograma — Contratos no SuperSing — Passo a Passo.png"),
  },
  {
    id: "controle-pacientes-iclinic-sharepoint",
    areaId: "enfermagem",
    titulo: "Controle de Pacientes - iClinic e SharePoint",
    setor: "Enfermagem",
    responsavel: "Juliana Bonato",
    categoria: "Acompanhamento",
    resumo: "Acompanhamento de pacientes em tratamento usando iClinic, SharePoint e chat corporativo.",
    etapas: ["Medicações no iClinic", "Contatos de acompanhamento", "Finalização", "Calendário SharePoint", "Comunicação e bioimpedância"],
    tarefasSugeridas: [
      "Registrar medicação e criar lembretes de acompanhamento.",
      "Fazer contatos de 30 e 60 dias, além de contatos semanais para doses programadas.",
      "Registrar pendências no calendário SharePoint e usar apenas canais corporativos.",
    ],
    tags: ["iClinic", "SharePoint", "tratamento", "bioimpedância"],
    fileName: "Fluxograma — Controle de Pacientes - iClinic e SharePoint.png",
    assetPath: fluxogramaPath("Fluxograma — Controle de Pacientes - iClinic e SharePoint.png"),
  },
  {
    id: "flebotomia-terapeutica",
    areaId: "enfermagem",
    titulo: "Flebotomia Terapêutica (Sangria Terapêutica)",
    setor: "Enfermagem",
    responsavel: "Equipe de Enfermagem",
    categoria: "Procedimento assistencial",
    resumo: "Coleta terapêutica para remoção de volume ou produtos do metabolismo, com monitoramento e registro.",
    etapas: ["Preparo", "Acesso venoso", "Coleta e monitoramento", "Encerramento"],
    tarefasSugeridas: [
      "Conferir prescrição, dados do paciente, volume e sinais vitais.",
      "Montar bolsa de sangria, controlar vazão e atingir volume prescrito.",
      "Descartar bolsa, orientar paciente e registrar anotação de enfermagem.",
    ],
    tags: ["sangria", "sinais vitais", "descarte", "registro"],
    fileName: "Fluxograma — Flebotomia Terapeutica (Sangria Terapeutica).png",
    assetPath: fluxogramaPath("Fluxograma — Flebotomia Terapeutica (Sangria Terapeutica).png"),
  },
  {
    id: "fluxo-pre-pos-consulta",
    areaId: "gestao",
    titulo: "Fluxo Operacional Pré e Pós-Consulta do Paciente",
    setor: "Gestão",
    responsavel: "Gestão",
    categoria: "Experiência do paciente",
    resumo: "Da chegada à entrega final, com excelência no acolhimento, documentação, adesão e pós-venda.",
    etapas: ["Pré-consulta", "Consulta e conduta", "Paciente aderiu", "Conferência e não adesão", "Entrega final e pós-venda"],
    tarefasSugeridas: [
      "Conferir cadastro, assinatura, documentos e bioimpedância.",
      "Registrar valor/desconto, encaminhar receitas e montar presente quando houver adesão.",
      "Conferir contrato e garantir entrega final com pós-venda D+1.",
    ],
    tags: ["gestão", "pré-consulta", "pós-consulta", "adesão"],
    fileName: "Fluxograma — Fluxo Operacional Pré e Pós-Consulta do Paciente.png",
    assetPath: fluxogramaPath("Fluxograma — Fluxo Operacional Pré e Pós-Consulta do Paciente.png"),
  },
  {
    id: "jornada-paciente-alto-ticket",
    areaId: "recepcao_comercial",
    titulo: "Jornada do Paciente e Fechamento Alto Ticket - Protocolo Bratan",
    setor: "Recepção",
    responsavel: "Recepção / Secretaria",
    categoria: "Alto ticket",
    resumo: "Captação, qualificação, consulta premium, fechamento e acompanhamento contínuo.",
    etapas: ["Captação e qualificação", "Consulta e experiência premium", "Fechamento alto ticket", "Pós-venda e acompanhamento"],
    tarefasSugeridas: [
      "Aplicar script obrigatório e filtrar perfil alto ticket.",
      "Preparar recepção, kit paciente e condução sem pressa.",
      "Fazer transição, tratar objeções, fechar e manter responsável pelo paciente.",
    ],
    tags: ["alto ticket", "vendas", "pós-venda", "qualificação"],
    fileName: "Fluxograma — Jornada do Paciente e Fechamento Alto Ticket - Protocolo Bratan.png",
    assetPath: fluxogramaPath("Fluxograma — Jornada do Paciente e Fechamento Alto Ticket - Protocolo Bratan.png"),
  },
  {
    id: "alimentos-prontos-paciente",
    areaId: "copa_nutricao",
    titulo: "Controle de Alimentos Prontos para Oferta ao Paciente",
    setor: "Higienização / Copa (Nutrição)",
    responsavel: "Equipe responsável pela copa / recepção",
    categoria: "Segurança alimentar",
    resumo: "Seleção, higienização, embalagem, identificação e armazenamento de frutas e lanches naturais.",
    etapas: ["Selecionar e receber", "Higienizar", "Montar e identificar", "Armazenar e rastrear"],
    tarefasSugeridas: [
      "Selecionar fornecedor e recusar matéria-prima inadequada.",
      "Higienizar manipulação, lavar em água corrente e sanitizar com hipoclorito.",
      "Etiquetar, refrigerar entre 4 e 8 °C e registrar rastreabilidade.",
    ],
    tags: ["alimentos", "validade", "temperatura", "rastreabilidade"],
    fileName: "Fluxograma — POP-ALIM-01 Controle de Alimentos Prontos para Oferta ao Paciente.png",
    assetPath: fluxogramaPath("Fluxograma — POP-ALIM-01 Controle de Alimentos Prontos para Oferta ao Paciente.png"),
  },
  {
    id: "montagem-lanche-natural",
    areaId: "copa_nutricao",
    titulo: "Montagem de Lanche Natural Integral",
    setor: "Higienização / Copa (Nutrição)",
    responsavel: "Copa / colaborador responsável",
    categoria: "Segurança alimentar",
    resumo: "Montagem do sanduíche natural com pré-produção conferida, embalagem identificada e refrigeração imediata.",
    etapas: ["Pré-produção", "Montar", "Embalar e identificar", "Controle de qualidade"],
    tarefasSugeridas: [
      "Conferir geladeira, bancada, mãos, luvas, validade e abertura dos insumos.",
      "Montar no momento correto, embalar imediatamente e etiquetar com data e responsável.",
      "Descartar produto vencido, alterado ou fora de refrigeração.",
    ],
    tags: ["lanche", "copa", "validade", "refrigeração"],
    fileName: "Fluxograma — POP-ALIM-01 Montagem de Lanche Natural Integral.png",
    assetPath: fluxogramaPath("Fluxograma — POP-ALIM-01 Montagem de Lanche Natural Integral.png"),
  },
  {
    id: "emissao-receitas-compra-medicamentos",
    areaId: "enfermagem",
    titulo: "Emissão de Receitas para Compra de Medicamentos",
    setor: "Enfermagem / Compras",
    responsavel: "Assistente Administrativo / Compras",
    categoria: "Compras clínicas",
    resumo: "Prescrições vinculadas a pacientes reais, na quantidade exata da compra e com registro em planilha.",
    etapas: ["Identificar pacientes", "Emitir no Memed", "Segurança e envio", "Controle"],
    tarefasSugeridas: [
      "Identificar pacientes reais com indicação e nunca emitir em nome de colaboradores.",
      "Emitir receita no Memed com quantidade exata e desativar envio automático ao paciente.",
      "Enviar ao fornecedor e registrar compra na planilha com prazo e responsável.",
    ],
    tags: ["receitas", "Memed", "compras", "medicamentos"],
    fileName: "Fluxograma — POP-ENF · Etapa 2 Emissão de Receitas para Compra de Medicamentos.png",
    assetPath: fluxogramaPath("Fluxograma — POP-ENF · Etapa 2 Emissão de Receitas para Compra de Medicamentos.png"),
  },
  {
    id: "compras-estoque-medicamentos",
    areaId: "enfermagem",
    titulo: "Compras e Controle de Estoque de Medicamentos",
    setor: "Enfermagem / Compras",
    responsavel: "Enfermagem + Compras + Dr. Daniel",
    categoria: "Estoque",
    resumo: "Do relatório de estoque à entrada da mercadoria, com validação clínica, receitas e rastreabilidade.",
    etapas: ["Levantamento", "Validar e aprovar", "Comprar", "Receber e arquivar"],
    tarefasSugeridas: [
      "Receber relatório e conferir mínimo, vencimentos e consumo dos últimos 30 dias.",
      "Montar lista preliminar, obter aprovação do Dr. Daniel e providenciar receitas.",
      "Solicitar orçamento, comprar, lançar no SharePoint e dar entrada no iClinic.",
    ],
    tags: ["estoque", "compras", "iClinic", "SharePoint"],
    fileName: "Fluxograma — POP-ENF Compras e Controle de Estoque de Medicamentos.png",
    assetPath: fluxogramaPath("Fluxograma — POP-ENF Compras e Controle de Estoque de Medicamentos.png"),
  },
  {
    id: "fechamento-financeiro-diario",
    areaId: "financeiro_administrativo",
    titulo: "Fechamento Financeiro Diário",
    setor: "Financeiro / Administrativo",
    responsavel: "Setor Financeiro",
    categoria: "Fechamento",
    resumo: "Conferência, conciliação, classificação, registro e arquivamento do movimento do dia.",
    etapas: ["Coletar", "Conferir e conciliar", "Classificar e registrar", "Emitir e fechar"],
    tarefasSugeridas: [
      "Reunir comandas, receitas, comprovantes, contratos e documentos do crediário.",
      "Conferir agenda, adesão, composição do plano, valores e formas de pagamento.",
      "Classificar entradas, taxas, rendimentos, atualizar PDCA/P12 e arquivar NFS-e.",
    ],
    tags: ["financeiro", "conciliação", "NFS-e", "P12"],
    fileName: "Fluxograma — POP-FIN-001 Fechamento Financeiro Diário.png",
    assetPath: fluxogramaPath("Fluxograma — POP-FIN-001 Fechamento Financeiro Diário.png"),
  },
  {
    id: "agendamento-primeira-consulta",
    areaId: "recepcao_comercial",
    titulo: "Agendamento de Primeira Consulta e Apresentação do Plano Bratan",
    setor: "Gestão",
    responsavel: "Secretaria Premium / Gestão",
    categoria: "Agendamento",
    resumo: "Agendamento, registro e acompanhamento da primeira consulta com qualidade.",
    etapas: ["Recepção e qualificação", "Agendamento", "Registro e comunicação", "Acompanhamento e encerramento"],
    tarefasSugeridas: [
      "Receber lead, apresentar Instituto e coletar dados obrigatórios.",
      "Oferecer datas dentro do prazo, explicar condições e confirmar pagamento.",
      "Cadastrar no iClinic, enviar guia, atualizar controles e confirmar D-2/D-1.",
    ],
    tags: ["agendamento", "lead", "iClinic", "confirmação"],
    fileName: "Fluxograma — POP-GES-001 Agendamento de Primeira Consulta e Apresentação do Plano Bratan.png",
    assetPath: fluxogramaPath("Fluxograma — POP-GES-001 Agendamento de Primeira Consulta e Apresentação do Plano Bratan.png"),
  },
  {
    id: "controle-temperatura-geladeira",
    areaId: "higienizacao_limpeza",
    titulo: "Controle de Temperatura da Geladeira",
    setor: "Higienização / Limpeza",
    responsavel: "Andrya Naara",
    categoria: "Controle ambiental",
    resumo: "Monitoramento do termômetro digital para conservação adequada dos alimentos.",
    etapas: ["Instalação e preparo", "Configuração", "Leitura e monitoramento"],
    tarefasSugeridas: [
      "Manter equipamento fixado e cabo preservado.",
      "Ler unidade em Celsius, limpar/resetar quando necessário e substituir pilha se preciso.",
      "Observar temperaturas interna e externa e agir se sair da faixa.",
    ],
    tags: ["geladeira", "temperatura", "alimentos", "monitoramento"],
    fileName: "Fluxograma — POP. HIG - 005 Controle de Temperatura da Geladeira.png",
    assetPath: fluxogramaPath("Fluxograma — POP. HIG - 005 Controle de Temperatura da Geladeira.png"),
  },
  {
    id: "esterilizacao-instrumental",
    areaId: "enfermagem",
    titulo: "Esterilização de Instrumental",
    setor: "Enfermagem",
    responsavel: "Profissionais da Enfermagem",
    categoria: "Esterilização",
    resumo: "Limpeza e esterilização do instrumental para reduzir carga microbiana e garantir reuso seguro.",
    etapas: ["Limpeza e descontaminação", "Inspeção e embalagem", "Esterilização em autoclave"],
    tarefasSugeridas: [
      "Higienizar mãos, usar EPIs, detergente enzimático, escovar, enxaguar e secar.",
      "Inspecionar integridade, embalar em papel grau cirúrgico e identificar.",
      "Executar ciclo de autoclave, aguardar despressurização e conferir embalagens.",
    ],
    tags: ["esterilização", "autoclave", "instrumental", "EPI"],
    fileName: "Fluxograma — POP.ENF 002 Esterilização de Instrumental.png",
    assetPath: fluxogramaPath("Fluxograma — POP.ENF 002 Esterilização de Instrumental.png"),
  },
  {
    id: "uso-dea",
    areaId: "enfermagem",
    titulo: "Uso do DEA (Desfibrilador Externo Automático)",
    setor: "Enfermagem",
    responsavel: "Enfermeira Beatriz",
    categoria: "Emergência",
    resumo: "Aplicação do DEA em parada cardiorrespiratória, com análise de ritmo e suporte mantido.",
    etapas: ["Preparação", "Análise do ritmo", "Desfibrilação", "Situações especiais"],
    tarefasSugeridas: [
      "Ligar o DEA, instalar eletrodos e seguir áudio/visor em sequência.",
      "Garantir que ninguém toque no paciente durante análise e choque.",
      "Reiniciar compressões e manter suporte até retorno do paciente ou chegada do SAV.",
    ],
    tags: ["DEA", "emergência", "desfibrilação", "SAV"],
    fileName: "Fluxograma — Uso do DEA (Desfibrilador Externo Automático).png",
    assetPath: fluxogramaPath("Fluxograma — Uso do DEA (Desfibrilador Externo Automático).png"),
  },
];

export const totalPopsTasks = popsAreas.reduce((total, area) => total + area.tarefasDoDia.length, 0);

export function documentsByArea(areaId: PopsAreaId) {
  return fluxogramas.filter((documento) => documento.areaId === areaId);
}
